---
driver: 
  name: vagrant
provisioner:
  name: chef_solo
platforms:
  - name: ubuntu-14.04
    driver_config:
      username: ubuntu
suites:
  - name: hello_world
    run_list:
      - recipe[hw_goapp]
    attributes:
      go:
        owner: "ubuntu",
        packages: 
          - "github.com/cvlc/hello_world"
